"""Small async helpers for Home Assistant Recorder operations."""

from __future__ import annotations

import asyncio
from collections.abc import Callable, Iterable, Mapping
from datetime import datetime
import re
from typing import Any

RECORDER_OPERATION_TIMEOUT = 10

_VALID_STATISTIC_ID = re.compile(
    r"^(?!.+__)(?!_)[\da-z_]+(?<!_):(?!_)[\da-z_]+(?<!_)$"
)


def validate_energy_statistics_imports(
    batches: Iterable[
        tuple[Mapping[str, Any], Iterable[Mapping[str, Any]]]
    ],
) -> None:
    """Validate every replacement batch before a destructive clear.

    This mirrors the synchronous checks performed by Home Assistant's
    ``async_add_external_statistics`` for the energy-only batches generated by
    this integration. Validating the complete set first makes the subsequent
    enqueue callbacks non-failing under the supported Recorder API.
    """
    for metadata, statistics in batches:
        statistic_id = metadata.get("statistic_id")
        if (
            not isinstance(statistic_id, str)
            or _VALID_STATISTIC_ID.fullmatch(statistic_id) is None
        ):
            raise ValueError("Invalid statistic_id")

        source, _object_id = statistic_id.split(":", 1)
        if metadata.get("source") != source:
            raise ValueError("Invalid statistics source")
        if metadata.get("mean_type") is None:
            raise ValueError("Missing statistics mean_type")
        if metadata.get("unit_class") != "energy":
            raise ValueError("Invalid energy statistics unit_class")
        if metadata.get("unit_of_measurement") != "kWh":
            raise ValueError("Invalid energy statistics unit")

        for statistic in statistics:
            start = statistic.get("start")
            if (
                not isinstance(start, datetime)
                or start.tzinfo is None
                or start.utcoffset() is None
            ):
                raise ValueError("Statistics start must be timezone-aware")
            if start.minute or start.second or start.microsecond:
                raise ValueError("Statistics start must be on the hour")

            last_reset = statistic.get("last_reset")
            if last_reset is not None and (
                not isinstance(last_reset, datetime)
                or last_reset.tzinfo is None
                or last_reset.utcoffset() is None
            ):
                raise ValueError(
                    "Statistics last_reset must be timezone-aware"
                )


async def async_clear_statistics(
    recorder: Any,
    statistic_ids: Iterable[str],
    *,
    validate_followup: Callable[[], None] | None = None,
    enqueue_followup: Callable[[], None] | None = None,
    on_done: Callable[[], None] | None = None,
) -> bool:
    """Queue a clear and its replacement before waiting for confirmation.

    Recorder operations are FIFO jobs. The clear cannot be cancelled after it
    has been queued, so any required replacement must be queued synchronously
    behind it before this coroutine reaches its first suspension point.
    """
    if validate_followup is not None:
        validate_followup()

    ordered_ids = sorted(set(statistic_ids))
    if not ordered_ids:
        if enqueue_followup is not None:
            enqueue_followup()
        if on_done is not None:
            on_done()
        return True

    done_event = asyncio.Event()
    loop = asyncio.get_running_loop()

    def _finish_clear() -> None:
        try:
            if on_done is not None:
                on_done()
        finally:
            done_event.set()

    def _clear_done() -> None:
        loop.call_soon_threadsafe(_finish_clear)

    recorder.async_clear_statistics(ordered_ids, on_done=_clear_done)
    if enqueue_followup is not None:
        enqueue_followup()
    try:
        await asyncio.wait_for(
            done_event.wait(),
            timeout=RECORDER_OPERATION_TIMEOUT,
        )
    except asyncio.TimeoutError:
        return False
    return True
